### ISSUE TITLE
Homework feedback - HTML/CSS - week 2

### ISSUE THREAD

**Issue by senner008** [mag-da-lenka/hyf-homework#1]
Hi :)
Great homework
I can see that you are creative and have a great eye for details. 
Try to look at the comments and then re-commit and think about how to minimize the code. 
Please ask if you have questions
Keep it up!

**Comment by mag-da-lenka** [comment]
Hi :) 
Thank you for your time and feedback.  I will definitely work more on this exercise as I find it too complicated at times. I'll do my best to write a cleaner and more minimalist code.  When it comes to aesthetics, I chose to keep it simple because I prefer to focus on structure before I gain some more confidence.    

Thank you again for sharing your knowledge and experience.  

Coding is fun :)
